//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMplus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRMplus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một nhân viên đã được thêm. Bạn có muốn tiếp tục?.
        /// </summary>
        internal static string ADD_EMPLOYEE {
            get {
                return ResourceManager.GetString("ADD_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin hợp đồng đã được thêm..
        /// </summary>
        internal static string ADD_LABOUR_CONTRACT {
            get {
                return ResourceManager.GetString("ADD_LABOUR_CONTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm được hợp đồng này..
        /// </summary>
        internal static string ADD_LABOUR_CONTRACT_ERROR {
            get {
                return ResourceManager.GetString("ADD_LABOUR_CONTRACT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ loại này đã tồn tại..
        /// </summary>
        internal static string ADDRESS_EXIST {
            get {
                return ResourceManager.GetString("ADDRESS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chọn một phòng ban chuyển đến..
        /// </summary>
        internal static string CHOOSE_DEPARTMENT {
            get {
                return ResourceManager.GetString("CHOOSE_DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Việc khóa sổ sẽ không cho phép tính lại lương. Chức năng này chỉ nên thực hiện khi tính lương tháng mới. Bạn đồng ý khóa sổ?.
        /// </summary>
        internal static string CLOSE_SALARY {
            get {
                return ResourceManager.GetString("CLOSE_SALARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Collapse_large {
            get {
                object obj = ResourceManager.GetObject("Collapse_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn xóa nhân viên này?.
        /// </summary>
        internal static string DELETE_EMPLOYEE {
            get {
                return ResourceManager.GetString("DELETE_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa được nhân viên này..
        /// </summary>
        internal static string DELETE_EMPLOYEE_ERROR {
            get {
                return ResourceManager.GetString("DELETE_EMPLOYEE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng đã được xóa..
        /// </summary>
        internal static string DELETE_LABOUR_CONTRACT {
            get {
                return ResourceManager.GetString("DELETE_LABOUR_CONTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa được hợp đồng này..
        /// </summary>
        internal static string DELETE_LABOUR_CONTRACT_ERROR {
            get {
                return ResourceManager.GetString("DELETE_LABOUR_CONTRACT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn xóa hợp đồng này?.
        /// </summary>
        internal static string DELETE_LABOUR_CONTRACT_QUESTION {
            get {
                return ResourceManager.GetString("DELETE_LABOUR_CONTRACT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn xóa các tham số của nhân viên này?.
        /// </summary>
        internal static string DELETE_PARAMETER_EMPLOYEE {
            get {
                return ResourceManager.GetString("DELETE_PARAMETER_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn xóa nhóm tham số này?.
        /// </summary>
        internal static string DELETE_PARAMETER_GROUP {
            get {
                return ResourceManager.GetString("DELETE_PARAMETER_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn xóa tham số này?.
        /// </summary>
        internal static string DELETE_PARAMETER_SYSTEM {
            get {
                return ResourceManager.GetString("DELETE_PARAMETER_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chọn trùng với phòng ban cũ..
        /// </summary>
        internal static string DUPLICATION_DEPARTMENT {
            get {
                return ResourceManager.GetString("DUPLICATION_DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin hợp đồng đã đã được sửa..
        /// </summary>
        internal static string EDIT_LABOUR_CONTRACT {
            get {
                return ResourceManager.GetString("EDIT_LABOUR_CONTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa được hợp đồng này..
        /// </summary>
        internal static string EDIT_LABOUR_CONTRACT_ERROR {
            get {
                return ResourceManager.GetString("EDIT_LABOUR_CONTRACT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên này đã tồn tại..
        /// </summary>
        internal static string EMPLOYEE_EXIST {
            get {
                return ResourceManager.GetString("EMPLOYEE_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban này đã được chọn..
        /// </summary>
        internal static string EXISTS_DEPARTMENT {
            get {
                return ResourceManager.GetString("EXISTS_DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Expand_large {
            get {
                object obj = ResourceManager.GetObject("Expand_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy mẫu chấm công..
        /// </summary>
        internal static string EXPORT_EXCEL_ERROR {
            get {
                return ResourceManager.GetString("EXPORT_EXCEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FillDownHS {
            get {
                object obj = ResourceManager.GetObject("FillDownHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FillUpHS {
            get {
                object obj = ResourceManager.GetObject("FillUpHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu không thành công. Xin kiểm tra lại tệp Excel.
        /// </summary>
        internal static string IMPORT_EXCEL_ERROR {
            get {
                return ResourceManager.GetString("IMPORT_EXCEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập dữ liệu thành công.
        /// </summary>
        internal static string IMPORT_EXCEL_SUCCESS {
            get {
                return ResourceManager.GetString("IMPORT_EXCEL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không hợp lệ..
        /// </summary>
        internal static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sử dụng không tồn tại trong hệ thống..
        /// </summary>
        internal static string INVALID_USER {
            get {
                return ResourceManager.GetString("INVALID_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải chọn tham số..
        /// </summary>
        internal static string NO_PARAMETER_EMPLOYEE {
            get {
                return ResourceManager.GetString("NO_PARAMETER_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu lương chưa có! Bạn có muốn chuyển sang?.
        /// </summary>
        internal static string NO_SALARY_DATA {
            get {
                return ResourceManager.GetString("NO_SALARY_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nophoto {
            get {
                object obj = ResourceManager.GetObject("nophoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại loại này đã tồn tại..
        /// </summary>
        internal static string PHONE_EXIST {
            get {
                return ResourceManager.GetString("PHONE_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap run_icon {
            get {
                object obj = ResourceManager.GetObject("run_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển phòng ban bị lỗi..
        /// </summary>
        internal static string TRANSFER_DEPARTMENT_ERROR {
            get {
                return ResourceManager.GetString("TRANSFER_DEPARTMENT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã chuyển phòng ban thành công..
        /// </summary>
        internal static string TRANSFER_DEPARTMENT_SUCCESS {
            get {
                return ResourceManager.GetString("TRANSFER_DEPARTMENT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật được thông tin nhân viên..
        /// </summary>
        internal static string UPDATE_EMPLOYEE_ERROR {
            get {
                return ResourceManager.GetString("UPDATE_EMPLOYEE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin nhân viên đã được cập nhật..
        /// </summary>
        internal static string UPDATE_EMPLOYEE_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_EMPLOYEE_SUCCESS", resourceCulture);
            }
        }
    }
}
